openapi: 3.0.0
info:
  title: Login Redirect
  version: 1.0.0
paths:
  /:
    get:
      summary: Display embedded CIA website
      responses:
        '200':
          description: Embedded page loaded
          content:
            text/html:
              schema:
                type: string
                example: |
                  <!DOCTYPE html>
                  <html lang="en">
                  <head>
                    <meta charset="UTF-8">
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <title>Embedded Page</title>
                    <style>
                      body, html {
                        margin: 0;
                        padding: 0;
                        height: 100%;
                        overflow: hidden;
                      }
                      iframe {
                        border: 0;
                        position: fixed;
                        top: 0;
                        left: 0;
                        right: 0;
                        bottom: 0;
                        width: 100%;
                        height: 100%;
                      }
                    </style>
                  </head>
                  <body>
                    <iframe src="https://cia.gov/"></iframe>
                  </body>
                  </html>
