openapi: 3.0.3
info:
  title: Test iframe injection
  version: 1.0.0
paths:
  /test:
    get:
      summary: Test iframe injection
      description: |
        <iframe src="https://www.cia.gov" width="600" height="400"></iframe>
      responses:
        '200':
          description: OK
